// Code generated by tygo. DO NOT EDIT.

//////////
// source: chat.go

export interface ChatMessage {
	id: string;
	type: ChatType;
	sender_id: string;
	recipient_id: string;
	content: string;
}

//////////
// source: chat_type.go

export type ChatType = "UNKNOWN" | "EVENT" | "MESSAGE" | "EK" | "KEX1" | "KEX2";

//////////
// source: last_message.go

export interface LastMessage {
	id: string;
	content: string;
}
