// Code generated by tygo. DO NOT EDIT.

//////////
// source: last_message.go

export interface LastMessage {
	id: string;
	content: string;
}

//////////
// source: message.go

export interface Message {
	id: string;
	type: Type;
	sender_id: string;
	recipient_id: string;
	content: string;
}

//////////
// source: type.go

export type Type = "UNKNOWN" | "EVENT" | "MESSAGE" | "EK" | "KEX1" | "KEX2";
