// Code generated by tygo. DO NOT EDIT.

//////////
// source: http_response.go

export interface HttpResponse<T extends any> {
	code: number /* int */;
	status: string;
	desc?: string;
	errors?: string[];
	payloads?: T[];
}
