// Code generated by tygo. DO NOT EDIT.

//////////
// source: http_response.go

interface HttpResponseBase<T extends any> {
	code: number /* int */;
	status: string;
	desc: string;
	errors?: string[];
	payloads?: T[];
}

export type HttpResponse<T> = T extends null
	? HttpResponseBase<T> & { payloads?: never }
	: HttpResponseBase<T> & { payloads: T[] };

