// Code generated by tygo. DO NOT EDIT.

//////////
// source: pubkey_challenge.go

export interface PKCRequest {
	id: string;
	pk: string;
}
export interface PKCSignedRequest extends PKCRequest {
	token: string;
	signature: string;
}

//////////
// source: registering_user.go

export interface RegisteringUser {
	username: string;
	email: string;
	pubkey: string;
}
