// Code generated by tygo. DO NOT EDIT.
import { Pagination } from "./pagination"

//////////
// source: auth.go

export interface Auth {
	id: string;
	username: string;
}
export interface LoginReq {
	token: string;
}
export interface Session {
	id: string;
	is_current: boolean;
	created: string;
	expires: string;
	ip: string;
	string: string;
}
export interface AccessSession {
	id: string;
	created: string;
	expires: string;
	parent: Session;
}
export type SessionsList = { [key: string]: Session};

//////////
// source: pagination.go

export interface PaginatedData<T extends any> {
	data: T[];
	pagination: Pagination;
}

//////////
// source: registered_user.go

export interface RegisteredUser {
	id: string;
	username: string;
	redacted_email: string;
	pk_fingerprint: string;
}

//////////
// source: room_member.go

export interface RoomMember {
	id: string;
	username: string;
	display_name: string;
	is_me: boolean;
	role: string;
	is_online: boolean;
}

//////////
// source: userinfo.go

export interface UInfo {
	id: string;
	pubkey: string;
	username: string;
	display_name: string;
}
