// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth.go

export interface Auth {
	id: string;
	username: string;
}
export interface LoginReq {
	token: string;
}
export interface Session {
	id: string;
	is_current: boolean;
	created: string;
	expires: string;
	ip: string;
	string: string;
}
export interface AccessSession {
	id: string;
	created: string;
	expires: string;
	parent: Session;
}
export type SessionsList = { [key: string]: Session};

//////////
// source: registered_user.go

export interface RegisteredUser {
	id: string;
	username: string;
	redacted_email: string;
	pk_fingerprint: string;
}

//////////
// source: userinfo.go

export interface UInfo {
	id: string;
	pubkey: string;
	username: string;
	display_name: string;
}
