// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth.go

export interface Auth {
	id: string;
	username: string;
}
export interface LoginReq {
	token: string;
}

//////////
// source: registered_user.go

export interface RegisteredUser {
	id: string;
	username: string;
	redacted_email: string;
	pk_fingerprint: string;
}
