// Code generated by tygo. DO NOT EDIT.

//////////
// source: role.go

export type Role = "MEMBER" | "MODERATOR" | "OWNER";

//////////
// source: room.go

export interface Room {
	created_at: string;
	updated_at: string;
	id: string;
	participants: { [rid: string]: Role};
}
