// Code generated by tygo. DO NOT EDIT.
import { FFIMethods } from "../vaultlib_ffi";
//////////
// source: keystore.go

export interface KeyStore extends FFIMethods {
	sk: string;
	pk: string;
	fingerprint: string;
}
