// Code generated by tygo. DO NOT EDIT.
import { ExportedGo } from "../exported_go";
//////////
// source: keystore.go

export interface KeyStore extends ExportedGo {
	sk: string;
	pk: string;
	fingerprint: string;
}
