// Code generated by tygo. DO NOT EDIT.
import { KeyStore } from "./keystore";
import { ExportedGo } from "../exported_go";

//////////
// source: evault.go

export interface EVault extends ExportedGo {
	id: string;
	subject: string;
	sec_type: "NONE" | "ENC_KEY" | "PASSPHRASE" | "QR" | "BIOMETRICS" | "HW_KEY";
	salt: string;
	payload_size: number /* uint64 */;
	payload: string;
}

//////////
// source: vault.go

export interface Vault extends ExportedGo {
	id: string;
	subject: string;
	last_mod: string;
	dev_ident: string;
	note: string;
	kstore: KeyStore;
}
