// Code generated by tygo. DO NOT EDIT.

//////////
// source: evault.go

export interface IEVault {
	id: string;
	subject: string;
	sec_type: "NONE" | "ENC_KEY" | "PASSPHRASE" | "QR" | "BIOMETRICS" | "HW_KEY";
	salt: string;
	payload_size: number /* uint64 */;
	payload: string;
}

//////////
// source: vault.go

export interface IVault<T extends any> {
	id: string;
	subject: string;
	last_mod: string;
	dev_ident: string;
	note: string;
	kstore: T;
}
